[project]
name = "netkeeper4srun"
version = "0.1.6"
description = "Login script for srun network"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["loguru==0.7.2", "requests==2.32.3"]

[project.scripts]
srun-refresh = "netkeeper4srun.cli:refresh"
srun-check = "netkeeper4srun.cli:check"
